# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~

        newsletter:
            quality: 70
            filters:
                thumbnail: { size: [100, 120] }

        flag:
            quality: 70
            filters:
                thumbnail: { size: [40, 40] }

        mini:
            quality: 70
            filters:
                thumbnail: { size: [80, 80] }

        miniatures:
            quality: 70
            filters:
                thumbnail: { size: [200, 200] }

        miniatures_5on3:
            quality: 70
            filters:
                thumbnail: { size: [333, 200] }

        medium_size:
            quality: 70
            filters:
                thumbnail: { size: [500, 400] }

