vich_uploader:
    db_driver: orm

    mappings:
       products_images:
           uri_prefix: '%app.path.images%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           upload_destination: '%kernel.project_dir%/public/images/products'
